using System;

using UnityEngine;

using static Root;
using static Root.CursorType;

using static Cursor;

public class Highlightable : MonoBehaviour
{
    public Window window;
    public Region region;
    public Tooltip tooltip;

    //Saved reference to the renderer to avoid
    public SpriteRenderer render, additionalRender;

    //Events regarding 
    public Action<Highlightable> pressEvent, rightPressEvent, middlePressEvent;

    //Used to come back to default colour when mouse exits the collider
    public Color defaultColor;

    //Indicates the current state of the button
    public string pressedState;

    public void Initialise(Region region, Action<Highlightable> pressEvent, Action<Highlightable> rightPressEvent, Func<Highlightable, Action> tooltip, Action<Highlightable> middlePressEvent)
    {
        render = GetComponent<SpriteRenderer>();
        pressedState = "None";
        this.pressEvent = pressEvent;
        this.rightPressEvent = rightPressEvent;
        this.middlePressEvent = middlePressEvent;
        if (this != null && tooltip != null) this.tooltip = new Tooltip(() => this, tooltip);
        this.region = region;
        if (region != null) window = region.regionGroup.window;
    }

    public void OnMouseEnter()
    {
        if (defaultColor.a == 0) defaultColor = GetComponent<SpriteRenderer>().color;
        if (cursor.IsNow(None)) return;
        SetMouseOver(this);
        if (pressedState == "None" && tooltip != null) CDesktop.SetTooltip(tooltip);
        if (GetComponent<InputCharacter>() != null) cursor.SetCursor(Write);
        else if (pressedState != "None") cursor.SetCursor(Click);
        render.color = defaultColor - new Color(0.1f, 0.1f, 0.1f, 0);
        if (additionalRender != null) additionalRender.color = defaultColor - new Color(0.1f, 0.1f, 0.1f, 0);
    }

    public void OnMouseExit()
    {
        if (cursor.IsNow(None)) return;
        SetMouseOver(null);
        CloseWindow("Tooltip");
        Root.tooltip = null;
        if (cursor.IsNow(Click) || cursor.IsNow(Write))
            cursor.SetCursor(Default);
        render.color = defaultColor;
        if (additionalRender != null) additionalRender.color = defaultColor;
        pressedState = "None";
    }

    public void MouseDown(string key)
    {
        if (cursor.IsNow(None)) return;
        CloseWindow("Tooltip");
        Root.tooltip = null;
        cursor.SetCursor(Click);
        render.color = defaultColor - new Color(0.2f, 0.2f, 0.2f, 0);
        if (additionalRender != null) additionalRender.color = defaultColor - new Color(0.2f, 0.2f, 0.2f, 0);
        pressedState = key;
    }

    public void MouseUp(string key)
    {
        if (cursor.IsNow(None)) return;
        if (pressedState != key) return;
        cursor.SetCursor(Default);
        render.color = defaultColor - (mouseOver == this ? new Color(0.1f, 0.1f, 0.1f, 0) : new Color(0, 0, 0, 0));
        if (additionalRender != null) additionalRender.color = defaultColor - (mouseOver == this ? new Color(0.1f, 0.1f, 0.1f, 0) : new Color(0, 0, 0, 0));
        if (pressedState == "Left" && pressEvent != null)
        {
            var l = GetComponent<LineSmallButton>();
            pressEvent(this);
        }
        else if (pressedState == "Right" && rightPressEvent != null)
        {
            if (GetComponent<LineCheckbox>() != null)
                GetComponent<LineCheckbox>().RightClick();
            else rightPressEvent(this);
        }
        else if (pressedState == "Right" && GetComponent<LineCheckbox>() != null)
        {
            GetComponent<LineCheckbox>().RightClick();
        }
        else if (pressedState == "Middle" && middlePressEvent != null)
        {
            middlePressEvent(this);
        }
        pressedState = "None";
        if (window != null) window.Respawn(true);
    }
}
